### ISSUE TITLE
Как написать стоплосс при входе в позицию?

### ISSUE THREAD

**Issue by dishu1** [qwertyo1/tinkoff-trading-bot#9]
Добавляю в вашего бота торговлю по индикатору, с выставлением стоплосса при открытии всех позиций.
В примере market_order_stop_order.py к invest-python наблюдаю следующее:
```
from tinkoff.invest import (
    Client,
    OrderDirection,
    OrderExecutionReportStatus,
    OrderType,
    PostOrderResponse,
    StopOrderDirection,
    StopOrderExpirationType,
    StopOrderType,
)
```
У вас же написано:
```
from tinkoff.invest.grpc.orders_pb2 import (
    ORDER_DIRECTION_SELL,
    ORDER_DIRECTION_BUY,
    ORDER_TYPE_MARKET,
)
```
Почему именно так, и как мне использовать этот пример?
```
take_profit_response = client.stop_orders.post_stop_order(
        quantity=QUANTITY,
        price=decimal_to_quotation(take_profit_price),
        stop_price=decimal_to_quotation(take_profit_price),
        direction=StopOrderDirection.STOP_ORDER_DIRECTION_SELL,
        account_id=account_id,
        stop_order_type=StopOrderType.STOP_ORDER_TYPE_TAKE_PROFIT,
        instrument_id=INSTRUMENT_ID,
        expire_date=now() + STOP_ORDER_EXPIRE_DURATION,
        expiration_type=EXPIRATION_TYPE,
    )
```

**Comment by qwertyo1** [comment]
Здравствуйте. Спасибо за сообщение.

Я постараюсь ответить на этой неделе. На выходных не дошли руки.

**Comment by qwertyo1** [comment]
Прошу прощения за подний ответ.

Клиент не поддерживает выставление стоп-заявок. В описании [сервиса работы со стоп-заявками](https://tinkoff.github.io/investAPI/head-stoporders/) команда рекомендует не пользоваться этим сервисом, а обрабатывать заявки на покупку и продажу непосредственно в коде стратегии. Это и сделано в моей демонстрационной стратегии.

Но вы можете смело добавить нужную функцию в клиент `app/client.py` и затем использовать её в вашей стратегии. Если решите это сделать, то можете создать pull request в этот репозиторий с изменениями клиента.

**Comment by dishu1** [comment]
Спасибо. Известны причины почему сервисом не рекомендовано пользоваться?

**Comment by qwertyo1** [comment]
> Спасибо. Известны причины почему сервисом не рекомендовано пользоваться?

Я могу лишь предположить. Думаю, что это затрудняет контролирование сделок. Стоп-заявки выполняются автоматически на сервере и боту придётся следить за ее статусом, что, в целом, равносильно мониторингу условий и выставлению ордера самим ботом в момент когда условия подходящие :)
